name: futureproof
favicon: null
layout_spectrum: 0.88095
typography_spectrum: 0.5488742492161691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
