name: futureproof
favicon: null
layout_spectrum: 0.7340135227423161
typography_spectrum: 0.5488742492161691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.777464960468933
  lightness: 0.507153068901971
  saturation: 0.20633872644975781
  rhythmicContrast: 0.3975390400737524
purpose: []
